from __future__ import annotations

import argparse
import json
from dataclasses import dataclass
from datetime import UTC, datetime
from pathlib import Path
from typing import Any


@dataclass(frozen=True)
class ManifestStats:
    ids_trace_count: int
    incremental_rows: int
    unique_trace_ids: int
    duplicates_dropped: int
    missing_from_incremental: int


def _read_json(path: Path) -> dict[str, Any]:
    if not path.exists():
        raise FileNotFoundError(f"Missing JSON file: {path}")
    data = json.loads(path.read_text(encoding="utf-8"))
    if not isinstance(data, dict):
        raise ValueError(f"Expected JSON object in {path}")
    return data


def _read_jsonl(path: Path) -> list[dict[str, Any]]:
    if not path.exists():
        raise FileNotFoundError(f"Missing JSONL file: {path}")
    rows: list[dict[str, Any]] = []
    with path.open("r", encoding="utf-8") as f:
        for raw in f:
            line = raw.strip()
            if not line:
                continue
            try:
                row = json.loads(line)
            except json.JSONDecodeError:
                continue
            if isinstance(row, dict):
                rows.append(row)
    return rows


def _dedupe_latest(rows: list[dict[str, Any]]) -> dict[str, dict[str, Any]]:
    latest: dict[str, dict[str, Any]] = {}
    for row in rows:
        trace_id = row.get("trace_id")
        if isinstance(trace_id, str) and trace_id:
            latest[trace_id] = row
    return latest


def _chunked(items: list[str], size: int) -> list[list[str]]:
    if size <= 0:
        raise ValueError("chunk size must be positive")
    return [items[i : i + size] for i in range(0, len(items), size)]


def main() -> int:
    parser = argparse.ArgumentParser(description="Prepare canonical Phoenix trace manifest and shards.")
    parser.add_argument(
        "--ids-json",
        type=Path,
        default=Path("outputs/phoenix_traces_2026-04-20_ids.json"),
        help="Trace IDs JSON generated by incremental fetch script.",
    )
    parser.add_argument(
        "--incremental-jsonl",
        type=Path,
        default=Path("outputs/phoenix_traces_2026-04-20_incremental.jsonl"),
        help="Incremental per-trace JSONL artifact.",
    )
    parser.add_argument(
        "--manifest-out",
        type=Path,
        default=Path("outputs/phoenix_traces_2026-04-20_trace_manifest.json"),
        help="Canonical manifest output path.",
    )
    parser.add_argument(
        "--raw-out",
        type=Path,
        default=Path("outputs/phoenix_traces_2026-04-20_analyst_raw.jsonl"),
        help="Deduplicated per-trace JSONL output path (canonical analyst input).",
    )
    parser.add_argument(
        "--per-trace-dir",
        type=Path,
        default=Path("outputs/phoenix_traces_2026-04-20_traces"),
        help="Directory for one normalized trace payload per file.",
    )
    parser.add_argument(
        "--shards-out",
        type=Path,
        default=Path("outputs/phoenix_traces_2026-04-20_shards.json"),
        help="Shard definition JSON path.",
    )
    parser.add_argument(
        "--shard-size",
        type=int,
        default=40,
        help="Number of traces per shard.",
    )
    args = parser.parse_args()

    ids_payload = _read_json(args.ids_json)
    ids_list_raw = ids_payload.get("trace_ids")
    if not isinstance(ids_list_raw, list):
        raise ValueError("trace_ids missing or invalid in ids JSON")
    trace_ids = sorted({tid for tid in ids_list_raw if isinstance(tid, str) and tid})

    rows = _read_jsonl(args.incremental_jsonl)
    latest_by_id = _dedupe_latest(rows)

    missing_trace_ids = [tid for tid in trace_ids if tid not in latest_by_id]
    present_trace_ids = [tid for tid in trace_ids if tid in latest_by_id]

    stats = ManifestStats(
        ids_trace_count=len(trace_ids),
        incremental_rows=len(rows),
        unique_trace_ids=len(latest_by_id),
        duplicates_dropped=max(0, len(rows) - len(latest_by_id)),
        missing_from_incremental=len(missing_trace_ids),
    )

    args.raw_out.parent.mkdir(parents=True, exist_ok=True)
    args.per_trace_dir.mkdir(parents=True, exist_ok=True)

    with args.raw_out.open("w", encoding="utf-8") as f:
        for trace_id in present_trace_ids:
            row = latest_by_id[trace_id]
            f.write(json.dumps(row, ensure_ascii=False) + "\n")

            per_trace_payload = {
                "trace_id": trace_id,
                "row": row,
            }
            per_trace_path = args.per_trace_dir / f"{trace_id}.json"
            per_trace_path.write_text(json.dumps(per_trace_payload, ensure_ascii=False, indent=2), encoding="utf-8")

    shard_groups = _chunked(present_trace_ids, args.shard_size)
    shard_records: list[dict[str, Any]] = []
    for idx, group in enumerate(shard_groups, start=1):
        shard_records.append(
            {
                "shard_id": f"shard_{idx:03d}",
                "trace_count": len(group),
                "trace_ids": group,
            }
        )

    manifest = {
        "generated_at_utc": datetime.now(tz=UTC).isoformat(),
        "project": ids_payload.get("project"),
        "target_day_utc": ids_payload.get("target_day_utc"),
        "base_url": ids_payload.get("base_url"),
        "stats": {
            "ids_trace_count": stats.ids_trace_count,
            "incremental_rows": stats.incremental_rows,
            "unique_trace_ids": stats.unique_trace_ids,
            "duplicates_dropped": stats.duplicates_dropped,
            "missing_from_incremental": stats.missing_from_incremental,
        },
        "present_trace_ids": present_trace_ids,
        "missing_trace_ids": missing_trace_ids,
        "canonical_raw_jsonl": str(args.raw_out),
        "per_trace_dir": str(args.per_trace_dir),
        "shards_file": str(args.shards_out),
        "shard_size": args.shard_size,
        "shard_count": len(shard_records),
    }

    args.manifest_out.parent.mkdir(parents=True, exist_ok=True)
    args.manifest_out.write_text(json.dumps(manifest, ensure_ascii=False, indent=2), encoding="utf-8")

    shards_payload = {
        "generated_at_utc": datetime.now(tz=UTC).isoformat(),
        "trace_count": len(present_trace_ids),
        "shard_size": args.shard_size,
        "shard_count": len(shard_records),
        "shards": shard_records,
    }
    args.shards_out.parent.mkdir(parents=True, exist_ok=True)
    args.shards_out.write_text(json.dumps(shards_payload, ensure_ascii=False, indent=2), encoding="utf-8")

    print(f"Manifest: {args.manifest_out}")
    print(f"Canonical raw JSONL: {args.raw_out}")
    print(f"Per-trace dir: {args.per_trace_dir}")
    print(f"Shards file: {args.shards_out}")
    print(
        "Stats: "
        f"ids={stats.ids_trace_count}, rows={stats.incremental_rows}, unique={stats.unique_trace_ids}, "
        f"deduped={stats.duplicates_dropped}, missing={stats.missing_from_incremental}, shards={len(shard_records)}"
    )
    return 0


if __name__ == "__main__":
    raise SystemExit(main())